name: Unit tests
on:
  push:
    branches: [ master ]
    paths:
      - "**.py"
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: sagemath/sagemath:latest
      options: --user root
    steps:
      - name: Checkout Hodge diamond cutter
        uses: actions/checkout@v4
      - name: Install the Hodge diamond cutter
        run: sage --pip install .
      - name: Run the tests in Hodge diamond cutter
        run: sage -t diamond/diamond.py
